### ISSUE TITLE
Icon URL in site extension package doesn't work over https

### ISSUE THREAD

**Issue by davidebbo** [gregjhogan/selenium-grid-hub-site-extension#2]
The image URL for your package works as http, but fails as https. Try https://www.seleniumhq.org/images/selenium-grid-logo.png. Any chance of fixing that? The Azure portal is making changes that causes the icon to be broken in this case.

Thanks!

**Comment by gregjhogan** [comment]
@davidebbo thanks for the heads up! I updated the icon URL to use HTTPS.

**Comment by davidebbo** [comment]
Verified, thanks!
